[package]
name = "challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
foldhash = "0.2.0"
num_cpus = "1.17.0"

[profile.release]
codegen-units = 1
lto = "fat"

[profile.profiling]
inherits = "release"
debug = true
